### ISSUE TITLE
[Anon] Bug report: Age of Sigmar.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1836] opened 2021-05-24 16:27 UTC
**File:** Age of Sigmar.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The new gravelords update doesn't make graveguard battleline if the wight king is the general.

**Comment by rweyrauch** [comment] 2021-05-24 23:13
Duplicate of #1834.

**Closed by rweyrauch** 2021-05-24 23:13 UTC
