### ISSUE TITLE
[Anon] Bug report: Order - Fyreslayers.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1412] opened 2020-07-24 22:02 UTC
**File:** Order - Fyreslayers.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Double exposing because was not sure where to report. Generally, a player is allowed to add any unit with a matching title to a battallion, ignoring subcaptions (pg. 13 of the rules). This is not allowed in several places, particularly FS files. For instance, a warrior kinband is allowed to take a runeson on magmadroth. This is not permitted in the files currently.

**Comment by cartag** [comment] 2020-07-25 16:36
Duplicate of #1411 

I just checked from a fresh data update, and I'm showing the Warrior Kinband does have the option. When was the last time you updated your data? 

![image](https://user-images.githubusercontent.com/4388344/88461664-a9da6300-ce62-11ea-8678-b5e4512c3382.png)

**Closed by cartag** 2020-07-25 16:36 UTC
