### ISSUE TITLE
[Anon] Bug report: Chaos - Skaven.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1208] opened 2020-01-07 02:02 UTC
**File:** Chaos - Skaven.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** When General is Masterclan or Clans Skryre, selecting Stormfiends will move them from Battleline to Others.

**Comment by cartag** [comment] 2020-01-07 02:22
Duplicate of #1201.

**Closed by cartag** 2020-01-07 02:22 UTC
