### ISSUE TITLE
Death - Soulblight Gravelords: Conditional Battleline

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2048] opened 2021-07-10 03:12 UTC
Upon choosing a lineage for your force, conditional battleline entries show up in the selector as expected(i.e. Blood Knights for Kastelai or Terrorgheists in Avengorii). However, upon adding any units to the force, it will duplicate the entry in the selector.

**Comment by rweyrauch** [comment] 2021-07-10 03:46
This is a duplicate of #1937.

**Closed by rweyrauch** 2021-07-10 03:46 UTC
