### ISSUE TITLE
Idoneth Deepkin Mount Traits

### ISSUE THREAD

**Issue by PBobovsky** [BSData/warhammer-age-of-sigmar#3054] opened 2023-03-03 14:39 UTC
Idoneth Deepkin army can choose ONE Leviadon and ONE Deepmare trait. 

In BS if you select one of each, it rises a warning about only being able to choose one.

**Comment by rweyrauch** [comment] 2023-03-03 18:20
Duplicate of #3052

**Closed by rweyrauch** 2023-03-03 18:20 UTC
