### ISSUE TITLE
[Anon] Bug report: Age of Sigmar.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#122] opened 2017-06-09 17:24 UTC
**File:** Age of Sigmar.gstz

**BattleScribe version:** 2.01.00

**Platform:** Windows

**Dropbox:** No

**Description:** Stormcast Eternals Protector has no points. It should be 200 points.

**Comment by StealthKnightSteg** [comment] 2017-06-21 14:41
duplicate of #104

**Closed by StealthKnightSteg** 2017-06-21 14:41 UTC
Labels: duplicate
