### ISSUE TITLE
[Anon] Bug report: Destruction - Orruk Warclans.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1916] opened 2021-07-05 05:02 UTC
**File:** Destruction - Orruk Warclans.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Orruk Warclans gutrippaz are double the points they should be. If I go into the description they say 180 points but when I leave even though there's 10 of them they are 360 points.

**Comment by cartag** [comment] 2021-07-05 05:04
Thanks for reporting this! Duplicate of #1911, already fixed just hadn't been released yet.

**Closed by cartag** 2021-07-05 05:04 UTC
