### ISSUE TITLE
[Anon] Bug report: Destruction - Beastclaw Raiders.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1735] opened 2021-03-14 17:37 UTC
**File:** Destruction - Beastclaw Raiders.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** the boulderheard allegiance allows you to have many mount-traits on many characters however battlescrib displays an error when you select several mount-traits

**Comment by cartag** [comment] 2021-03-14 17:38
Duplicate of #1732.

**Closed by cartag** 2021-03-14 17:38 UTC
