### ISSUE TITLE
SERAPHON - Skink Spell Fiery Convocation

### ISSUE THREAD

**Issue by elric81** [BSData/warhammer-age-of-sigmar#2222] opened 2021-08-12 02:39 UTC
The spell must say "pick 1 ENEMY unit WITHIN 18 "of the caster" instead of "pick 1 FRIENDLY WHOLLY WITHIN 18" of the caster"

**Comment by rweyrauch** [comment] 2021-08-12 04:32
Duplicate of #2218.

**Closed by rweyrauch** 2021-08-12 04:32 UTC
Labels: Area: text/rule/profile, 💾 Order
