### ISSUE TITLE
[Anon] Bug report: Death - Flesh-eater Courts.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1348] opened 2020-06-10 20:27 UTC
**File:** Death - Flesh-eater Courts.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Grymwatch and Duke Crackmarrow are missing. They have warscrolls in the free app. Points are 120 for Duke and 0 for the Grymwatch, they are free but must have Duke Crackmarrow in your army to use them. This info is in the Warscroll builder on GW website. Thanks stay safe

**Comment by DrTobogganMD** [comment] 2020-06-17 13:39
Duplicate of #1306

**Closed by DrTobogganMD** 2020-06-17 13:39 UTC
Labels: Area:  selections, Resolution - Duplicate, Type: request, 💾 Death
