### ISSUE TITLE
[Anon] Bug report: Death - Soulblight Gravelords.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#2781] opened 2022-07-29 15:45 UTC
**File:** Death - Soulblight Gravelords.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** When creating a new Soulblight Gravelords army with the Pitched Battles GHB 22 force type, the Lore of the Deathmages and Lore of the Vampires spell lores don't appear, only an empty "Nighthaunt Spell Lore" box appears with nothing in it to be selected.

I.e. Vampires can't select a spell. Thanks in advance!

**Comment by rweyrauch** [comment] 2022-07-29 23:46
Unable to reproduce this error.   The 'Lore of the Vampires' is available to all vampires as expected.   Tested on Android and Linux.

**Comment by rweyrauch** [comment] 2022-07-30 17:05
Unable to reproduce - closing.

**Closed by rweyrauch** 2022-07-30 17:05 UTC
