### ISSUE TITLE
[Anon] Bug report: Age of Sigmar.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1861] opened 2021-06-04 01:11 UTC
**File:** Age of Sigmar.gstz

**BattleScribe version:** 2.02.37

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** For some reason in the legion of the first prince faction in chaos, furies arnt in the unit selection.

**Comment by cartag** [comment] 2021-06-04 01:37
Duplicate of #1862

**Closed by cartag** 2021-06-04 01:37 UTC
