### ISSUE TITLE
[Anon] Bug report: Chaos - Skaven.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1431] opened 2020-08-06 04:42 UTC
**File:** Chaos - Skaven.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Stormfiends do not show as CLANS MOULDER, and so they do not allow the clan moulder battleline (giant rats and rat ogors) if they're in an army list. they should be both CLANS SKYRE and CLANS MOULDER, even though they are only battleline for Skyre.

**Comment by jjmaximum** [comment] 2020-08-06 04:45
Whoops, this is a duplicate of #1323. Sorry for not checking before I submitted this.

**Closed** 2020-08-09 18:50 UTC
