### ISSUE TITLE
[Anon] Bug report: Chaos - Khorne.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#715] opened 2018-10-12 21:27 UTC
**File:** Chaos - Khorne.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I try to create an AOS Khorne list of any type it seems to crash the program on my iPad. I can load it on my Blackberry, but it always crashes when I try to create a Khorne list.

**Comment by rweyrauch** [comment] 2018-11-06 14:45
Duplicate of #687.

**Closed by rweyrauch** 2018-11-06 14:45 UTC
Labels: Resolution - Duplicate, 💾 Chaos
