### ISSUE TITLE
[Anon] Bug report: Age of Sigmar.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#555] opened 2018-07-05 05:18 UTC
**File:** Age of Sigmar.gstz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** The points cost for the Order - Bretonnia Field Trebuchet is 200 it should be 220 according to the GW Bretonnian War Scroll and ONLINE War Scrolls 2018 builder.

**Comment by rweyrauch** [comment] 2018-07-05 05:36
Duplicate of #556.

**Closed by rweyrauch** 2018-07-05 05:36 UTC
