### ISSUE TITLE
[Anon] Bug report: Order - Sylvaneth.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#769] opened 2019-01-16 00:34 UTC
**File:** Order - Sylvaneth.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** SPIRIT OF DURTHU IS NOT A NAMES CHARACTER HENCE HE CAN BE GIVEN ARTEFACT AND WARLORD TRAITS, BUT WHEN I USE REALM OF BATTLE GHYRAN I CANNOT GIVE HIM THE WARLORD TRAITS AND ANY ARTEFACT EVENTHOUGH I ALREADY SELECTED HIM AS THE GENERAL.

**Comment by rweyrauch** [comment] 2019-01-16 01:03
Duplicate of #765.

**Closed by rweyrauch** 2019-01-16 01:03 UTC
