### ISSUE TITLE
Seraphon Thunder lizard 

### ISSUE THREAD

**Issue by TemplarMarx** [BSData/warhammer-age-of-sigmar#2209] opened 2021-08-08 19:47 UTC
When attempting to make detachemnts using thunder lizard stegadon it is not removing the behemoth keyword. In these faction they should loss that and gain the battleline not have both.

**Comment by rweyrauch** [comment] 2021-08-08 20:35
Duplicate of #2201.
Fixed.

**Closed by rweyrauch** 2021-08-08 20:35 UTC

**Comment by TemplarMarx** [comment] 2021-08-08 21:17
I have updated my data however they still have the behemoth keyword
